# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
- develop

variables:
- name: SENTRY_AUTH_TOKEN
  value: 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 

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - task: Docker@2
      displayName: 'Build Docker image'
      inputs:
        command: 'build'
        repository: 'hychart'
        Dockerfile: '**/Dockerfile'
        buildContext: '.'
        tags: |
          latest
          $(Build.BuildId)
      condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/develop')))
    - task: ECRPushImage@1
      displayName: 'Push to ECR (latest)'
      inputs:
        awsCredentials: 'AWS-ECR-Connection'
        regionName: 'eu-west-1'
        imageSource: 'imagename'
        sourceImageName: 'hychart'
        sourceImageTag: 'latest'
        repositoryName: 'hychart'
        autoCreateRepository: true
        forceDockerNamingConventions: true
      condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/develop')))
    - task: ECRPushImage@1
      displayName: 'Push to ECR ($(Build.BuildId))'
      inputs:
        awsCredentials: 'AWS-ECR-Connection'
        regionName: 'eu-west-1'
        imageSource: 'imagename'
        sourceImageName: 'hychart'
        sourceImageTag: '$(Build.BuildId)'
        repositoryName: 'hychart'
        pushTag: '$(Build.BuildId)'
        autoCreateRepository: true
        forceDockerNamingConventions: true
        removeDockerImage: true
      condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/develop')))
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        Contents: |
          node-deploy.azure.yaml
          node-deploy.dev.azure.yaml
          node-deploy.vars.dev.json
          node-deploy.vars.prod.json
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
