apiVersion: v1
kind: Service
metadata:
  name: hychart-dev
  labels:
    app: hychart-dev
spec:
  selector:
    app: hychart-dev
  ports:
    - name: http
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hychart-dev
  labels:
    version: v1
spec:
  replicas: #{replicas}#
  selector:
    matchLabels:
      app: hychart-dev
  template:
    metadata:
      labels:
        app: hychart-dev
        version: v1
    spec:
      priorityClassName: low-priority
      containers:
        - name: hychart
          image: breadcrumbs.azurecr.io/hychart:#{Build.BuildId}#
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: #{cpu-limit}#
              memory: #{memory-limit}#
            requests:
              cpu: #{cpu}#
              memory: #{memory}#
          env:
            - name: LOGIN_URL
              value: "https://app.bcrumbs.net/account/login"
