export const SHORTCUT_KEYS = [
  'ctrl+alt+f',
  'ctrl+alt+c',
  'ctrl+alt+z',
  'ctrl+alt+x',
  'up',
  'down',
  'right',
  'left',
  'ctrl+alt+p',
  'ctrl+alt+r',
  'ctrl+alt+v',
  'ctrl+alt+n',
  'ctrl+alt+k',
  'ctrl',
];

export enum CanvasEvents {
  INIT = 'INIT',
  ADD_MODULE = 'ADD_MODULE',
  MOVE_MODULE = 'MOVE_MODULE',
  SELECT_MODULE = 'SELECT_MODULE',
  UPDATE_CONNECTIONS = 'UPDATE_CONNECTIONS',
  DELETE_MODULE = 'DELETE_MODULE',
}

export const DraggingEvents = {};

export const BLOCK_HEIGHT = 90;
export const BLOCK_WIDTH = 90;
export const NORMAL_BG = '#fefefe';
export const HOVER_BG = '#a0a0f0';

export const PredefinedEntities = [
  { value: 'sys.date', text: 'sys.date' },
  { value: 'sys.date-period', text: 'sys.date-period' },
  { value: 'sys.time', text: 'sys.time' },
  { value: 'sys.time-period', text: 'sys.time-period' },
  { value: 'sys.color', text: 'sys.color' },
  { value: 'sys.unit-currency', text: 'sys.unit-currency' },
  { value: 'sys.number', text: 'sys.number' },
  { value: 'sys.cardinal', text: 'sys.cardinal' },
  { value: 'sys.ordinal', text: 'sys.ordinal' },
  { value: 'sys.number-integer', text: 'sys.number-integer' },
  { value: 'sys.number-sequence', text: 'sys.number-sequence' },
  { value: 'sys.flight-number', text: 'sys.flight-number' },
  { value: 'sys.unit-area', text: 'sys.unit-area' },
  { value: 'sys.unit-length', text: 'sys.unit-length' },
  { value: 'sys.unit-speed', text: 'sys.unit-speed' },
  { value: 'sys.unit-volume', text: 'sys.unit-volume' },
  { value: 'sys.unit-weight', text: 'sys.unit-weight' },
  { value: 'sys.unit-information', text: 'sys.unit-information' },
  { value: 'sys.percentage', text: 'sys.percentage' },
  { value: 'sys.temperature', text: 'sys.percentage' },
  { value: 'sys.duration', text: 'sys.percentage' },
  { value: 'sys.age', text: 'sys.age' },
  { value: 'sys.currency-name', text: 'sys.currency-name' },
  { value: 'sys.unit-area-name', text: 'sys.unit-area-name' },
  { value: 'sys.unit-length-name', text: 'sys.unit-length-name' },
  { value: 'sys.unit-speed-name', text: 'sys.unit-speed-name' },
  { value: 'sys.unit-volume-name', text: 'sys.unit-volume-name' },
  { value: 'sys.unit-weight-name', text: 'sys.unit-weight-name' },
  { value: 'sys.unit-information-name', text: 'sys.unit-information-name' },
  { value: 'sys.address', text: 'sys.address' },
  { value: 'sys.street-address', text: 'sys.street-address' },
  { value: 'sys.zip-code', text: 'sys.zip-code' },
  { value: 'sys.geo-capital', text: 'sys.geo-capital' },
  { value: 'sys.geo-country', text: 'sys.geo-country' },
  { value: 'sys.geo-country-code', text: 'sys.geo-country-code' },
  { value: 'sys.geo-city', text: 'sys.geo-city' },
  { value: 'sys.geo-state', text: 'sys.geo-state' },
  { value: 'sys.geo-city-us', text: 'sys.geo-city-us' },
  { value: 'sys.geo-state-us', text: 'sys.geo-state-us' },
  { value: 'sys.geo-county-us', text: 'sys.geo-county-us' },
  { value: 'sys.geo-city-gb', text: 'sys.geo-city-gb' },
  { value: 'sys.geo-state-gb', text: 'sys.geo-state-gb' },
  { value: 'sys.geo-county-gb', text: 'sys.geo-county-gb' },
  { value: 'sys.place-attraction-us', text: 'sys.place-attraction-us' },
  { value: 'sys.place-attraction-gb', text: 'sys.place-attraction-gb' },
  { value: 'sys.place-attraction', text: 'sys.place-attraction' },
  { value: 'sys.airport', text: 'sys.airport' },
  { value: 'sys.location', text: 'sys.location' },
  { value: 'sys.email', text: 'sys.email' },
  { value: 'sys.phone-number', text: 'sys.phone-number' },
  { value: 'sys.given-name', text: 'sys.given-name' },
  { value: 'sys.last-name', text: 'sys.last-name' },
  { value: 'sys.person', text: 'sys.person' },
  { value: 'sys.music-artist', text: 'sys.music-artist' },
  { value: 'sys.music-genre', text: 'sys.music-genre' },
  { value: 'sys.language', text: 'sys.language' },
  { value: 'sys.any', text: 'sys.any' },
  { value: 'sys.url', text: 'sys.url' },
];
